imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: "@marmitonBundle/Resources/config/services.yml" }
    - { resource: "@utilisateursBundle/Resources/config/services.yml" }

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: fr


framework:
    #esi: ~ 
    translator: { fallback: '%locale%' }
    secret: '%secret%'
    router:
        resource: '%kernel.project_dir%/app/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    #serializer: { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale: '%locale%'
    trusted_hosts: ~
    session:
        # https://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id: session.handler.native_file
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
    fragments: ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true

fos_user:
    db_driver: orm 
    firewall_name: main
    user_class: utilisateursBundle\Entity\utilisateurs
    from_email:
        address: "noreply@belkadi.com"
        sender_name: "No Reply"

# Twig Configuration
twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'

# Doctrine Configuration
doctrine:
    dbal:
        driver: pdo_mysql
        host: '%database_host%'
        port: '%database_port%'
        dbname: '%database_name%'
        user: '%database_user%'
        password: '%database_password%'
        charset: UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.project_dir%/var/data/data.sqlite"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #path: '%database_path%'

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: '%mailer_transport%'
    host: '%mailer_host%'
    username: '%mailer_user%'
    password: '%mailer_password%'
    spool: { type: memory }


jms_i18n_routing:
    default_locale: fr
    locales: [fr, en]
    strategy: prefix_except_default 


hwi_oauth:
    # Define which firewalls will be used for oauth
    # Usually, its only the main, but you can add it if you have a custom one
    connect:
        account_connector: my.custom.user_provider
    firewall_names: ["main"]
    fosub:
        username_iterations: 30
        # Define in which columns of the fos_user table will be stored
        # the access token of every resource_owner
        properties:
            facebook: facebook_id
    resource_owners:
        facebook:
            type:           facebook
            client_id:           "1912237582365034"
            client_secret:       "7c5ead0ca88a0201fed6ae3dea5d8061"
            infos_url:     "https://graph.facebook.com/me?fields=id,name,email"

